# Generated by Django 4.0.3 on 2022-09-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.FloatField(null=True)),
                ('statistic', models.FloatField(null=True)),
                ('economic', models.FloatField(null=True)),
                ('discredit', models.FloatField(null=True)),
                ('symptons', models.FloatField(null=True)),
                ('society', models.FloatField(null=True)),
                ('politicization', models.FloatField(null=True)),
                ('celebrity', models.FloatField(null=True)),
                ('analisy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontendapi.analisy')),
            ],
        ),
        migrations.CreateModel(
            name='Disinformation',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, null=True)),
                ('choice', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontendapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='analisy',
            name='disinformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontendapi.disinformation'),
        ),
    ]
