# Generated by Django 4.0.3 on 2022-07-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disinformation',
            fields=[
                ('auto_increment_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=255)),
                ('tipo_analise', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontendapi.user')),
            ],
        ),
    ]
