# Generated by Django 4.0.3 on 2022-08-20 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapi', '0002_analisy_rename_nome_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disinformation',
            old_name='chave',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='disinformation',
            old_name='texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='disinformation',
            old_name='tipo_analise',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='disinformation',
            old_name='titulo',
            new_name='type_analysis',
        ),
    ]
